name: h3_flutter_example
description: Demonstrates how to use the h3_flutter plugin.

publish_to: 'none'
resolution: workspace

environment:
  sdk: '>= 3.5.0'

dependencies:
  flutter:
    sdk: flutter

  h3_flutter:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: # uses workspace's version

flutter:
  uses-material-design: true
