name: h3_dart_ffi_example
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '>= 3.5.0'

dependencies:
  h3_dart:
    path: ../..

dev_dependencies:
  lints: # uses workspace's version
