name: Publish to pub.dev, create tag and release

on:
  push:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# secrets.PUB_CREDENTIAL_JSON taken from "~/Library/Application Support/dart/pub-credentials.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package: [h3_common, geojson2h3, h3_ffi, h3_web, h3_dart, h3_flutter]
        include:
          - package: h3_common
            release_name: "H3 Common"
          - package: geojson2h3
            release_name: "Geojson2H3"
          - package: h3_ffi
            release_name: "H3 Ffi"
          - package: h3_web
            release_name: "H3 Web"
          - package: h3_dart
            release_name: "H3 Dart"
          - package: h3_flutter
            release_name: "H3 Flutter"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Remove symlinks
        run: h3_flutter/bindings/scripts/toggle_h3lib.sh
        if: matrix.package == 'h3_flutter'

      - name: Prebuild iOS & macOS library
        run: h3_flutter/bindings/scripts/build_darwin_static_lib.sh
        if: matrix.package == 'h3_flutter'

      - name: Pubspec Metadata
        uses: altive/pubspec-metadata@v1
        id: pubspec
        with:
          pubspec-file: ./${{ matrix.package }}/pubspec.yaml

      - id: get_existing_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ matrix.package }}_${{ steps.pubspec.outputs.version-number }}
        continue-on-error: true

      - name: Publish to pub
        uses: festelo/actions-flutter-pub-publisher@master
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          package_directory: ./${{ matrix.package }}
        if: steps.get_existing_release.outputs.id == null && (github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch')

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ matrix.release_name }} v${{ steps.pubspec.outputs.version-number }}"
          automatic_release_tag: "${{ matrix.package }}_${{ steps.pubspec.outputs.version-number }}"
        if: steps.get_existing_release.outputs.id == null && (github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch')
  